version: '3'
services:
  yyds:
    container_name: yyds
    image: iregistry.baidu-int.com/acg-acloud:1289d72-20210831-1125
    ports:
      - 17000:80
    environment:
      - OPEN_API=物理机ip:8687
    restart: always
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
